### ISSUE TITLE
Update to v1.7.0

### ISSUE THREAD

**Issue by CptPie** [strichliste/strichliste-docker#7]

**Comment by foorschtbar** [comment]
Same probleme here. After i changed release to 1.7.x, container brokes...

**Comment by madonius** [comment]
This should be closed/updated. Since 1.7.1 has been released.

**Comment by madonius** [comment]
My errors when trying to run with 1.7.x if it helps:
```
[21-Sep-2020 13:14:01] WARNING: [pool www] child 13 said into stderr: "2020-09-21T13:14:01+00:00 [critical] Class 'App\EventListener\ApiExceptionListener' not found"
[21-Sep-2020 13:14:01] WARNING: [pool www] child 13 said into stderr: "2020-09-21T13:14:01+00:00 [critical] Class 'App\EventListener\ApiExceptionListener' not found"
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ApiExceptionListener" from namespace "App\EventListener"."
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "Did you forget a "use" statement for another namespace? in /source/var/cache/prod/ContainerFBFbyqU/srcApp_KernelProdContainer.php:128"
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "Stack trace:"
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "#0 /source/vendor/symfony/event-dispatcher/EventDispatcher.php(294): ContainerFBFbyqU\srcApp_KernelProdContainer->ContainerFBFbyqU\{closure}()"
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "#1 /source/vendor/symfony/event-dispatcher/EventDispatcher.php(258): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...', Object(Symfony\Component\EventDispatcher\EventDispatcher))"
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "#2 /source/vendor/symfony/event-dispatcher/EventDispatcher.php(233): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\Component\HttpKernel\Event\ExceptionEvent))"
[21-Sep-2020 13:14:02] WARNING: [pool www] child 13 said into stderr: "#3 /source/vendor/..."
```
